filein "Controller.ms"
filein "Locator.ms"

Loc_LeftEyeCtrl = AddPoint "Loc_LeftEyeCtrl" 3 blue
Loc_LeftEyeCtrl.pos = [0, 0, 0] 

Loc_LeftEyeBone1 = AddPoint "Loc_LeftEyeBone1" 3 blue
Loc_LeftEyeBone1.pos = [-40, 0, 0] 
Loc_LeftEyeBone2 = AddPoint "Loc_LeftEyeBone2" 3 blue
Loc_LeftEyeBone2.pos = [-80, 0, 0] 
Loc_LeftEyeBone3 = AddPoint "Loc_LeftEyeBone3" 3 blue
Loc_LeftEyeBone3.pos = [-120, 0, 0]
